torchrun --nproc_per_node=8 --master_port=5553 train.py \
    --model_name_or_path "wxjiao/alpaca-7b" \
     --data_path ../../data/train/coi_2.json \
    --bf16 True \
    --output_dir ../../alpaca_models/coi2 \
    --num_train_epochs 3 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --deepspeed "./configs/default_offload_opt_param.json" \
    --tf32 True \
    --report_to "none"